# Generated by Django 6.0 on 2026-01-21 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('ability', models.PositiveIntegerField(verbose_name='Espacios disponibles')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_hours', models.PositiveSmallIntegerField(help_text='Tiempo mínimo en horas', verbose_name='Duración (horas)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto')),
                ('default', models.BooleanField(default=False, verbose_name='Activa por defecto')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
            },
        ),
        migrations.CreateModel(
            name='MonthlyPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('owner_name', models.CharField(max_length=150, verbose_name='Nombre del propietario')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto mensual')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Placa mensual',
                'verbose_name_plural': 'Placas mensuales',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10, verbose_name='Placa')),
                ('entry_date_hour', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de entrada')),
                ('departure_date_hour', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de salida')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_fee', to='parking.fee')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
        ),
    ]
