# Generated by Django 6.0 on 2026-01-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('billing_type', models.CharField(choices=[('HOURLY', 'Por hora'), ('DAILY', 'Diario fijo'), ('MONTHLY', 'Mensual')], max_length=10, verbose_name='Tipo de cobro')),
                ('daily_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Monto diario')),
                ('monthly_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Monto mensual')),
                ('owner_name', models.CharField(blank=True, max_length=150, verbose_name='Propietario')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Política de placa',
                'verbose_name_plural': 'Políticas de placas',
            },
        ),
    ]
