# Generated by Django 6.0 on 2026-01-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_platepolicy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platepolicy',
            name='daily_amount',
        ),
        migrations.RemoveField(
            model_name='platepolicy',
            name='monthly_amount',
        ),
        migrations.AddField(
            model_name='platepolicy',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto según tipo de cobro (diario o mensual)', max_digits=8, null=True, verbose_name='Monto'),
        ),
    ]
