# Generated by Django 6.0 on 2026-01-30 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_remove_platepolicy_daily_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyPlate',
        ),
    ]
