# Generated by Django 6.0 on 2026-01-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_delete_monthlyplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='billing_type',
            field=models.CharField(choices=[('HOURLY_BLOCK', 'Bloque por horas'), ('DAILY_FIXED', 'Monto fijo por día')], default='HOURLY_BLOCK', max_length=20, verbose_name='Tipo de cobro'),
        ),
    ]
