# Generated by Django 6.0 on 2026-02-09 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_fee_billing_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='billing_type',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='duration_hours',
        ),
    ]
