# Generated by Django 6.0 on 2026-02-09 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_remove_fee_billing_type_remove_fee_duration_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='amount',
        ),
        migrations.AddField(
            model_name='fee',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción de la tarifa', verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='fee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='fee',
            name='name',
            field=models.CharField(default=0, help_text='Nombre de la tarifa', max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_minute', models.PositiveIntegerField(verbose_name='Minuto inicial')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='parking.fee')),
            ],
            options={
                'verbose_name': 'Rango de tarifa',
                'verbose_name_plural': 'Rangos de tarifas',
            },
        ),
    ]
