# Generated by Django 6.0 on 2026-02-11 01:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_remove_fee_amount_fee_description_fee_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_date_hour',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de entrada'),
        ),
    ]
