# Generated by Django 6.0 on 2026-02-11 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_alter_entry_entry_date_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_date_hour',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 11, 1, 21, 53, 156399, tzinfo=datetime.timezone.utc), verbose_name='Fecha y hora de entrada'),
        ),
    ]
