# Generated by Django 6.0 on 2026-02-19 04:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_alter_entry_entry_date_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_date_hour',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de entrada'),
        ),
        migrations.AlterField(
            model_name='platepolicy',
            name='billing_type',
            field=models.CharField(choices=[('', '-Seleccione un tipo de cobro-'), ('HOURLY', 'Por hora'), ('DAILY', 'Diario fijo'), ('MONTHLY', 'Mensual')], max_length=10, verbose_name='Tipo de cobro'),
        ),
    ]
