# Generated by Django 6.0 on 2026-02-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_alter_entry_entry_date_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto calculado al momento de registrar la salida', max_digits=10, null=True, verbose_name='Monto final cobrado'),
        ),
        migrations.AddField(
            model_name='entry',
            name='final_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo total en minutos al momento de registrar la salida', null=True, verbose_name='Minutos finales'),
        ),
    ]
