# Generated by Django 6.0 on 2026-04-01 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_entry_final_amount_entry_final_minutes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'permissions': [('view_statistics_entry', 'Puede ver estadísticas de entradas')], 'verbose_name': 'Entrada', 'verbose_name_plural': 'Entradas'},
        ),
    ]
