# Generated by Django 6.0 on 2026-04-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0012_alter_entry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platepolicy',
            options={'permissions': [('view_statistics_placepolicy', 'Puede ver estadísticas de suscripciones')], 'verbose_name': 'Política de placa', 'verbose_name_plural': 'Políticas de placas'},
        ),
    ]
