from .views import (
    entry_edit_view,
    register,
    search_plate,
    departure,
    record,
    go_to_departure,
    subscription_plate_list,
    subscription_register,
    subscription_edit,
    toggle_subscription_active,
    imprimir_ticket,
    parking_generate_reports_form,
    report_day_pdf,
    report_month_pdf,
    report_period_pdf,
    report_plate_pdf,
)
from django.urls import path

urlpatterns = [
    path("busqueda/", search_plate, name="search_plate"),
    path("registro/<str:plate>", register, name="register"),
    path("salida/<int:pk>", departure, name="departure"),
    path("historial/", record, name="record"),
    path('go-to-departure/<int:pk>/', go_to_departure, name='go_to_departure'),
    path('editar/<int:pk>/', entry_edit_view, name='edit_entry'),
    path('suscripciones/', subscription_plate_list, name='subscription_plate_list'),
    path('suscripciones/registrar', subscription_register, name='subscription_register'),
    path('suscripciones/<int:pk>', subscription_edit, name='subscription_edit'),
    path('suscripciones/desactivar/<int:pk>', toggle_subscription_active, name='toggle_subscription_active'),
    path('suscripciones/activar/<int:pk>', toggle_subscription_active, name='toggle_subscription_active'),
    path('ticket/', imprimir_ticket),
    path('reportes/', parking_generate_reports_form, name='parking_reports'),
    path("reporte/hoy/", report_day_pdf, name="report_day_pdf"),
    path("reporte/mes/", report_month_pdf, name="report_month_pdf"),
    path("reporte/periodo/", report_period_pdf, name="report_period_pdf"),
    path("reporte/placa/", report_plate_pdf, name="report_plate_pdf"),
]
