# Generated by Django 6.0 on 2026-02-05 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BathroomFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la tarifa')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Monto')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='Color')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tarifa de Baño',
                'verbose_name_plural': 'Tarifas de Baños',
            },
        ),
        migrations.CreateModel(
            name='BathroomEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date_hour', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de entrada')),
                ('fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bathroom_entry_fee', to='bathrooms.bathroomfee')),
            ],
            options={
                'verbose_name': 'Entrada de Baño',
                'verbose_name_plural': 'Entradas de Baños',
            },
        ),
    ]
