# Generated by Django 6.0 on 2026-04-01 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bathrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bathroomentry',
            options={'permissions': [('view_statistics_bathroomentry', 'Puede ver estadísticas de uso de baños')], 'verbose_name': 'Entrada de Baño', 'verbose_name_plural': 'Entradas de Baños'},
        ),
    ]
