# Generated by Django 6.0 on 2026-07-10 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de activación de la suscripción')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la suscripción')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('active', models.BooleanField(default=False, verbose_name='Activo')),
                ('cancellation_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_date', models.DateField(verbose_name='Período de facturación')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto a pagar')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de pago')),
                ('paid', models.BooleanField(default=False, verbose_name='Pagado')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payment.subscription')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
